dist: bionic
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'nightly'
jobs:
  allow_failures:
    - python: 'nightly'
install:
  - pip install tox-travis
script: tox
notifications:
  email: false
